Repository manticoresoftware/manticoresearch, pull requests merged in 2024-03, with the labels that each got.

#1869 Buddy Protocol Upgrade to v2
  deps.txt
  src/searchdaemon.h
  src/searchdbuddy.cpp
  src/searchdhttp.cpp
  src/searchdhttp.h
  src/searchdhttpcompat.cpp
Labels: pack

#1904 Updated build/test images
  .github/workflows/test_template.yml
  .gitignore
  dist/build_dockers/cross/external_toolchain/Dockerfile
  manual/Installation/Compiling_from_sources.md
  misc/ctest/ubertests/Dockerfile
  misc/ctest/ubertests/sphinx
  test/ubertest.php
Labels: pack

#1946 Test/comparison of json overhead versus sql overhead
  .github/workflows/clt_nightly.yml
  test/clt-tests/comparison-overhead-json-sql/fnames.txt
  test/clt-tests/comparison-overhead-json-sql/load_us_names.php
  test/clt-tests/comparison-overhead-json-sql/names.txt
  test/clt-tests/comparison-overhead-json-sql/surnames.txt
  test/clt-tests/comparison-overhead-json-sql/test-comparison-overhead-json-sql.rec
Labels: done

#1540 Change logic to run Buddy in Docker on Windows
  .github/workflows/pack_publish.yml
  CMakeLists.txt
  config/config_cmake.h.in
  deps.txt
  dist/build_dockers/nsis/nsis_src_parser.sh
  dist/build_dockers/nsis/nsisscript.nsi
  src/replication/portrange.cpp
  src/replication/portrange.h
  src/searchd.cpp
  src/searchdbuddy.cpp
  src/searchdbuddy.h
  src/sphinxplugin.cpp
  src/sphinxutils.cpp
Labels: publish, pack
