Repository manticoresoftware/manticoresearch, pull requests merged in 2025-02, with the labels that each got.

#2964 Buddy's Demon Request Registration
  test/clt-tests/core/test-buddy-requests-not-logged.rec
Labels: done

#3066 Revert "fix build with static libraries"
  cmake/helpers.cmake
Labels: pack

#3072 Update test-supported-mysqldump-versions
  test/clt-tests/mysqldump/versions/test-supported-mysqldump-versions.rec
Labels: done

#3092 Fix test-migration-es-ms.rec and test-supported-mysqldump-versions…
  test/clt-tests/migration-es-ms/test-migration-es-ms.rec
  test/clt-tests/mysqldump/versions/script_versions.sh
  test/clt-tests/mysqldump/versions/test-supported-mysqldump-versions.rec
Labels: done

#3101 Update test-migration-es-ms.rec
  test/clt-tests/migration-es-ms/test-migration-es-ms.rec
Labels: enhancement

#2991 Created test-inconsistent-comunication-with-buddy.rec
  test/clt-tests/buddy/test-inconsistent-comunication-with-buddy.rec
Labels: done

#3104 Test/kibana manticore handling
  test/clt-tests/core/test-manticore-handling-id.rec
Labels: done

#3100 fix build with Boost 1.87.0
  src/searchdbuddy.cpp
Labels: pack

#3107 Created test-avg-select-join.rec
  test/clt-tests/join/test-avg-select-join.rec
Labels: done

#3147 Incorrect knn search by doc id
  test/clt-tests/buddy/test-knn-search-by-doc-id.rec
Labels: done
